# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/smdk4412-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/smdk4412-common/proprietary/bin/bcm4334.hcd:$(TARGET_COPY_OUT_SYSTEM)/bin/bcm4334.hcd \
    vendor/samsung/smdk4412-common/proprietary/bin/bcm4334_murata.hcd:$(TARGET_COPY_OUT_SYSTEM)/bin/bcm4334_murata.hcd \
    vendor/samsung/smdk4412-common/proprietary/bin/bcm4334_semco.hcd:$(TARGET_COPY_OUT_SYSTEM)/bin/bcm4334_semco.hcd \
    vendor/samsung/smdk4412-common/proprietary/cameradata/datapattern_420sp.yuv:$(TARGET_COPY_OUT_SYSTEM)/cameradata/datapattern_420sp.yuv \
    vendor/samsung/smdk4412-common/proprietary/cameradata/datapattern_front_420sp.yuv:$(TARGET_COPY_OUT_SYSTEM)/cameradata/datapattern_front_420sp.yuv \
    vendor/samsung/smdk4412-common/proprietary/etc/wifi/bcmdhd_apsta.bin_b2:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_apsta.bin_b2 \
    vendor/samsung/smdk4412-common/proprietary/etc/wifi/bcmdhd_mfg.bin_b2:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_mfg.bin_b2 \
    vendor/samsung/smdk4412-common/proprietary/etc/wifi/bcmdhd_p2p.bin_b2:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_p2p.bin_b2 \
    vendor/samsung/smdk4412-common/proprietary/etc/wifi/bcmdhd_sta.bin_b2:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_sta.bin_b2 \
    vendor/samsung/smdk4412-common/proprietary/etc/wifi/nvram_mfg.txt:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/nvram_mfg.txt \
    vendor/samsung/smdk4412-common/proprietary/etc/wifi/nvram_mfg.txt_murata:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/nvram_mfg.txt_murata \
    vendor/samsung/smdk4412-common/proprietary/etc/wifi/nvram_mfg.txt_semcosh:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/nvram_mfg.txt_semcosh \
    vendor/samsung/smdk4412-common/proprietary/etc/wifi/nvram_net.txt:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/nvram_net.txt \
    vendor/samsung/smdk4412-common/proprietary/etc/wifi/nvram_net.txt_murata:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/nvram_net.txt_murata \
    vendor/samsung/smdk4412-common/proprietary/etc/wifi/nvram_net.txt_semcosh:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/nvram_net.txt_semcosh \
    vendor/samsung/smdk4412-common/proprietary/lib/egl/libGLESv1_CM_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv1_CM_mali.so \
    vendor/samsung/smdk4412-common/proprietary/lib/egl/libGLESv2_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv2_mali.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libcec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcec.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libddc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libddc.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libedid.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libedid.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libMcClient.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libMcClient.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libMcRegistry.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libMcRegistry.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libMcVersion.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libMcVersion.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libsecnativefeature.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsecnativefeature.so \
    vendor/samsung/smdk4412-common/proprietary/usr/idc/melfas_ts.idc:$(TARGET_COPY_OUT_SYSTEM)/usr/idc/melfas_ts.idc \
    vendor/samsung/smdk4412-common/proprietary/usr/keylayout/gpio-keys.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/gpio-keys.kl \
    vendor/samsung/smdk4412-common/proprietary/usr/keylayout/sii9234_rcp.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/sii9234_rcp.kl \
    vendor/samsung/smdk4412-common/proprietary/vendor/firmware/fimc_is_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_fw.bin \
    vendor/samsung/smdk4412-common/proprietary/vendor/firmware/mfc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc_fw.bin \
    vendor/samsung/smdk4412-common/proprietary/vendor/firmware/setfile.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile.bin \

# Prebuilt Mali GPU driver
PRODUCT_PACKAGES += \
    libMali

